import type { AppraisalStoreState, DemoEmployee } from '@/lib/appraisal/types';

/** Active employees provisioned when HR opens a cycle. */
export const DEMO_EMPLOYEES: DemoEmployee[] = [
  {
    employeeId: 'EMP001',
    employeeName: 'Rajesh Kumar',
    employeeEmail: 'employee@company.com',
    department: 'Quality Assurance',
    designation: 'Senior QA Lead',
    managerId: 'MGR001',
  },
  {
    employeeId: 'EMP002',
    employeeName: 'Sneha Reddy',
    employeeEmail: 'employee2@company.com',
    department: 'Engineering',
    designation: 'Frontend Developer',
    managerId: 'MGR001',
  },
  {
    employeeId: 'EMP003',
    employeeName: 'Karthik Iyer',
    employeeEmail: 'employee3@company.com',
    department: 'Engineering',
    designation: 'Backend Developer',
    managerId: 'MGR001',
  },
];

/** Seeded against HRMS demo credentials / employee IDs. */
export function createInitialAppraisalState(): AppraisalStoreState {
  const cycleId = 'cycle-2026-annual';
  const now = new Date().toISOString();

  return {
    cycles: [
      {
        id: cycleId,
        name: '2026 Annual Appraisal Cycle',
        description: 'Full-year 2026 performance review. Employees can submit self-assessments now.',
        startDate: '2026-01-01',
        endDate: '2026-12-31',
        /** Open so employees can complete Self Appraisal immediately. */
        status: 'open',
      },
    ],
    competencies: [
      { id: '1', name: 'Technical Skills', description: 'Job-specific technical proficiency' },
      { id: '2', name: 'Quality of Work', description: 'Accuracy and craftsmanship' },
      { id: '3', name: 'Productivity', description: 'Output and efficiency' },
      { id: '4', name: 'Communication Skills', description: 'Clear written and verbal communication' },
      { id: '5', name: 'Teamwork & Collaboration', description: 'Works effectively with others' },
      { id: '6', name: 'Problem Solving', description: 'Analyzes and resolves issues' },
      { id: '7', name: 'Initiative & Ownership', description: 'Takes responsibility and drives outcomes' },
      { id: '8', name: 'Innovation & Creativity', description: 'Brings new ideas and improvements' },
      { id: '9', name: 'Time Management', description: 'Prioritization and delivery discipline' },
      { id: '10', name: 'Learning & Development', description: 'Continuous skill growth' },
      { id: '11', name: 'Adaptability & Flexibility', description: 'Handles change effectively' },
      { id: '12', name: 'Goal/KPI Achievement', description: 'Delivers against agreed goals' },
      {
        id: '13',
        name: 'Leadership',
        description: 'Guides and develops others',
        isLeadershipOnly: true,
      },
    ],
    goals: [
      {
        id: '1',
        employeeId: 'EMP001',
        managerId: 'MGR001',
        cycleId,
        name: 'Improve release quality',
        description: 'Reduce escaped defects in QA cycles.',
        kpi: 'Defect leakage < 3%',
        weightage: 40,
        target: '< 3% leakage',
        progress: 72,
        status: 'in_progress',
        dueDate: '2026-06-15',
      },
      {
        id: '2',
        employeeId: 'EMP001',
        managerId: 'MGR001',
        cycleId,
        name: 'Automation coverage',
        description: 'Expand regression automation for critical flows.',
        kpi: 'Automation coverage',
        weightage: 35,
        target: '70% coverage',
        progress: 58,
        status: 'in_progress',
        dueDate: '2026-06-20',
      },
      {
        id: '3',
        employeeId: 'EMP001',
        managerId: 'MGR001',
        cycleId,
        name: 'Mentorship',
        description: 'Mentor junior QA engineers on test design.',
        kpi: 'Mentorship sessions',
        weightage: 25,
        target: '8 sessions',
        progress: 80,
        status: 'in_progress',
        dueDate: '2026-06-30',
      },
      {
        id: '4',
        employeeId: 'EMP002',
        managerId: 'MGR001',
        cycleId,
        name: 'Platform modernization',
        description: 'Migrate legacy modules to Next.js services.',
        kpi: 'Modules migrated',
        weightage: 50,
        target: '4 modules',
        progress: 65,
        status: 'in_progress',
        dueDate: '2026-06-25',
      },
      {
        id: '5',
        employeeId: 'EMP002',
        managerId: 'MGR001',
        cycleId,
        name: 'Code quality',
        description: 'Improve maintainability and review standards.',
        kpi: 'Sonar issues',
        weightage: 50,
        target: 'Critical = 0',
        progress: 70,
        status: 'in_progress',
        dueDate: '2026-06-28',
      },
      {
        id: '6',
        employeeId: 'EMP003',
        managerId: 'MGR001',
        cycleId,
        name: 'API reliability',
        description: 'Improve uptime and error budgets for core services.',
        kpi: 'Service uptime',
        weightage: 55,
        target: '99.9% uptime',
        progress: 68,
        status: 'in_progress',
        dueDate: '2026-06-22',
      },
      {
        id: '7',
        employeeId: 'EMP003',
        managerId: 'MGR001',
        cycleId,
        name: 'Tech debt reduction',
        description: 'Refactor high-churn modules and reduce P1 incidents.',
        kpi: 'P1 incidents',
        weightage: 45,
        target: '< 2 / month',
        progress: 55,
        status: 'in_progress',
        dueDate: '2026-06-30',
      },
    ],
    appraisals: DEMO_EMPLOYEES.map((emp) => ({
      id: `apr-${emp.employeeId.toLowerCase()}`,
      employeeId: emp.employeeId,
      employeeName: emp.employeeName,
      employeeEmail: emp.employeeEmail,
      department: emp.department,
      designation: emp.designation,
      managerId: emp.managerId,
      cycleId,
      achievements: '',
      challenges: '',
      selfFeedback: '',
      selfRating: null,
      competencyRatings: [],
      goalRatings: [],
      status: 'draft' as const,
      updatedAt: now,
    })),
    managerReviews: [],
    adminReviews: [],
    leadershipReviews: [],
    notifications: [
      ...DEMO_EMPLOYEES.map((emp, index) => ({
        id: `notif-cycle-open-${emp.employeeId}-${index}`,
        recipientId: emp.employeeId,
        title: 'Appraisal cycle opened',
        message: '2026 Annual Appraisal Cycle is open. Please complete and submit your self-appraisal.',
        link: '/employee/self-appraisal',
        isRead: false,
        createdAt: now,
      })),
      {
        id: 'notif-cycle-open-mgr',
        recipientId: 'MGR001',
        title: 'Appraisal cycle opened',
        message: '2026 Annual Appraisal Cycle is open. Team self-appraisals will appear after employees submit.',
        link: '/manager/pending-reviews',
        isRead: false,
        createdAt: now,
      },
      {
        id: 'notif-cycle-open-hr',
        recipientId: 'HR001',
        title: 'Cycle opened',
        message: '2026 Annual Appraisal Cycle is open. Track Employee → Manager → Admin → CEO progress in Reports.',
        link: '/hr/reports',
        isRead: false,
        createdAt: now,
      },
    ],
  };
}
